//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Stock
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Склад.
    /// </summary>
    //  *** Start programmer edit section *** (Склад CustomAttributes)

    //  *** End programmer edit section *** (Склад CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СкладE", new string[] {
            "Адрес as \'Адрес\'",
            "работников as \'Работников\'"})]
    [AssociatedDetailViewAttribute("СкладE", "Товар", "ТоварE", true, "", "Товар", true, new string[] {
            ""})]
    [View("СкладL", new string[] {
            "Адрес as \'Адрес\'",
            "работников as \'Работников\'"})]
    public class Склад : ICSSoft.STORMNET.DataObject
    {
        
        private string fАдрес;
        
        private int fработников;
        
        private IIS.Stock.DetailArrayOfТовар fТовар;
        
        //  *** Start programmer edit section *** (Склад CustomMembers)

        //  *** End programmer edit section *** (Склад CustomMembers)

        
        /// <summary>
        /// Адрес.
        /// </summary>
        //  *** Start programmer edit section *** (Склад.Адрес CustomAttributes)

        //  *** End programmer edit section *** (Склад.Адрес CustomAttributes)
        [StrLen(255)]
        public virtual string Адрес
        {
            get
            {
                //  *** Start programmer edit section *** (Склад.Адрес Get start)

                //  *** End programmer edit section *** (Склад.Адрес Get start)
                string result = this.fАдрес;
                //  *** Start programmer edit section *** (Склад.Адрес Get end)

                //  *** End programmer edit section *** (Склад.Адрес Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Склад.Адрес Set start)

                //  *** End programmer edit section *** (Склад.Адрес Set start)
                this.fАдрес = value;
                //  *** Start programmer edit section *** (Склад.Адрес Set end)

                //  *** End programmer edit section *** (Склад.Адрес Set end)
            }
        }
        
        /// <summary>
        /// работников.
        /// </summary>
        //  *** Start programmer edit section *** (Склад.работников CustomAttributes)

        //  *** End programmer edit section *** (Склад.работников CustomAttributes)
        public virtual int работников
        {
            get
            {
                //  *** Start programmer edit section *** (Склад.работников Get start)

                //  *** End programmer edit section *** (Склад.работников Get start)
                int result = this.fработников;
                //  *** Start programmer edit section *** (Склад.работников Get end)

                //  *** End programmer edit section *** (Склад.работников Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Склад.работников Set start)

                //  *** End programmer edit section *** (Склад.работников Set start)
                this.fработников = value;
                //  *** Start programmer edit section *** (Склад.работников Set end)

                //  *** End programmer edit section *** (Склад.работников Set end)
            }
        }
        
        /// <summary>
        /// Склад.
        /// </summary>
        //  *** Start programmer edit section *** (Склад.Товар CustomAttributes)

        //  *** End programmer edit section *** (Склад.Товар CustomAttributes)
        public virtual IIS.Stock.DetailArrayOfТовар Товар
        {
            get
            {
                //  *** Start programmer edit section *** (Склад.Товар Get start)

                //  *** End programmer edit section *** (Склад.Товар Get start)
                if ((this.fТовар == null))
                {
                    this.fТовар = new IIS.Stock.DetailArrayOfТовар(this);
                }
                IIS.Stock.DetailArrayOfТовар result = this.fТовар;
                //  *** Start programmer edit section *** (Склад.Товар Get end)

                //  *** End programmer edit section *** (Склад.Товар Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Склад.Товар Set start)

                //  *** End programmer edit section *** (Склад.Товар Set start)
                this.fТовар = value;
                //  *** Start programmer edit section *** (Склад.Товар Set end)

                //  *** End programmer edit section *** (Склад.Товар Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СкладE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СкладE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СкладE", typeof(IIS.Stock.Склад));
                }
            }
            
            /// <summary>
            /// "СкладL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СкладL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СкладL", typeof(IIS.Stock.Склад));
                }
            }
        }
    }
}
