//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Stock
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Товар.
    /// </summary>
    //  *** Start programmer edit section *** (Товар CustomAttributes)

    //  *** End programmer edit section *** (Товар CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТоварE", new string[] {
            "Наименование as \'Наименование\'",
            "Количество as \'Количество\'",
            "Цена as \'Цена\'"})]
    public class Товар : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        private int fКоличество;
        
        private int fЦена;
        
        private IIS.Stock.Склад fСклад;
        
        //  *** Start programmer edit section *** (Товар CustomMembers)

        //  *** End programmer edit section *** (Товар CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        //  *** Start programmer edit section *** (Товар.Наименование CustomAttributes)

        //  *** End programmer edit section *** (Товар.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                //  *** Start programmer edit section *** (Товар.Наименование Get start)

                //  *** End programmer edit section *** (Товар.Наименование Get start)
                string result = this.fНаименование;
                //  *** Start programmer edit section *** (Товар.Наименование Get end)

                //  *** End programmer edit section *** (Товар.Наименование Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Товар.Наименование Set start)

                //  *** End programmer edit section *** (Товар.Наименование Set start)
                this.fНаименование = value;
                //  *** Start programmer edit section *** (Товар.Наименование Set end)

                //  *** End programmer edit section *** (Товар.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Количество.
        /// </summary>
        //  *** Start programmer edit section *** (Товар.Количество CustomAttributes)

        //  *** End programmer edit section *** (Товар.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                //  *** Start programmer edit section *** (Товар.Количество Get start)

                //  *** End programmer edit section *** (Товар.Количество Get start)
                int result = this.fКоличество;
                //  *** Start programmer edit section *** (Товар.Количество Get end)

                //  *** End programmer edit section *** (Товар.Количество Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Товар.Количество Set start)

                //  *** End programmer edit section *** (Товар.Количество Set start)
                this.fКоличество = value;
                //  *** Start programmer edit section *** (Товар.Количество Set end)

                //  *** End programmer edit section *** (Товар.Количество Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        //  *** Start programmer edit section *** (Товар.Цена CustomAttributes)

        //  *** End programmer edit section *** (Товар.Цена CustomAttributes)
        public virtual int Цена
        {
            get
            {
                //  *** Start programmer edit section *** (Товар.Цена Get start)

                //  *** End programmer edit section *** (Товар.Цена Get start)
                int result = this.fЦена;
                //  *** Start programmer edit section *** (Товар.Цена Get end)

                //  *** End programmer edit section *** (Товар.Цена Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Товар.Цена Set start)

                //  *** End programmer edit section *** (Товар.Цена Set start)
                this.fЦена = value;
                //  *** Start programmer edit section *** (Товар.Цена Set end)

                //  *** End programmer edit section *** (Товар.Цена Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Stock.Склад.
        /// </summary>
        //  *** Start programmer edit section *** (Товар.Склад CustomAttributes)

        //  *** End programmer edit section *** (Товар.Склад CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.Stock.Склад Склад
        {
            get
            {
                //  *** Start programmer edit section *** (Товар.Склад Get start)

                //  *** End programmer edit section *** (Товар.Склад Get start)
                IIS.Stock.Склад result = this.fСклад;
                //  *** Start programmer edit section *** (Товар.Склад Get end)

                //  *** End programmer edit section *** (Товар.Склад Get end)
                return result;
            }
            set
            {
                //  *** Start programmer edit section *** (Товар.Склад Set start)

                //  *** End programmer edit section *** (Товар.Склад Set start)
                this.fСклад = value;
                //  *** Start programmer edit section *** (Товар.Склад Set end)

                //  *** End programmer edit section *** (Товар.Склад Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТоварE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварE", typeof(IIS.Stock.Товар));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Товар.
    /// </summary>
    //  *** Start programmer edit section *** (DetailArrayDetailArrayOfТовар CustomAttributes)

    //  *** End programmer edit section *** (DetailArrayDetailArrayOfТовар CustomAttributes)
    public class DetailArrayOfТовар : ICSSoft.STORMNET.DetailArray
    {
        
        //  *** Start programmer edit section *** (IIS.Stock.DetailArrayOfТовар members)

        //  *** End programmer edit section *** (IIS.Stock.DetailArrayOfТовар members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Товар by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Товар.
        /// </summary>
        public DetailArrayOfТовар(IIS.Stock.Склад fСклад) : 
                base(typeof(Товар), ((ICSSoft.STORMNET.DataObject)(fСклад)))
        {
        }
        
        public IIS.Stock.Товар this[int index]
        {
            get
            {
                return ((IIS.Stock.Товар)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Stock.Товар dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
